const test = require('tape');
const { runTest } = require('./test-helpers');

test('Method verification test', async (t) => {
  const expectedOutput = `=== Method Verification Test ===
Testing InputStream methods...
InputStream methods: OK
Testing DataInputStream methods...
DataInputStream methods: OK
Testing File methods...
File methods: OK
Testing StringWriter methods...
StringWriter methods: OK
Testing PrintWriter methods...
PrintWriter methods: OK
Testing StringReader methods...
StringReader methods: OK
Testing EOFException methods...
EOFException methods: OK
Testing IOException methods...
IOException methods: OK
=== Verification Complete ===`;

  await runTest('MethodVerificationTest', expectedOutput, t);
});