'use strict';
const test=require('tape');
const {JVM}=require('../src/core/jvm');
test('prepared leaf-loop Wasm selection requires a full ready call-free module',t=>{
 const j=new JVM({jit:{compileWorker:false,preparedLoopLeafWasm:true}}),h=j.jit;
 const leaf={attributes:[{type:'code',code:{codeItems:[{instruction:'iconst_0',labelDef:'L0:'},{instruction:'pop'},{instruction:{op:'goto',arg:'L0'}}]}}]};
 const caller={attributes:[{type:'code',code:{codeItems:[{instruction:{op:'invokestatic',arg:['Method','F',['run','()V']]},labelDef:'L0:'},{instruction:{op:'goto',arg:'L0'}}]}}]};
 const straight={attributes:[{type:'code',code:{codeItems:[{instruction:'return'}]}}]};
 h.hasReadyFullWasmModule=()=>true;h.hasWasmExitStorm=()=>false;
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(leaf),false,'unprepared method is excluded');
 for(const m of [leaf,caller,straight])h.preparedCodegenMethods.add(m);
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(leaf),true,'ready full leaf loop admitted');
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(caller),false,'calls retain existing policy');
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(straight),false,'loop-free method retains existing policy');
 h.hasReadyFullWasmModule=()=>false;
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(leaf),false,'missing/partial module excluded');
 h.hasReadyFullWasmModule=()=>true;h.hasWasmExitStorm=()=>true;
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(leaf),false,'exit storm retains fallback');
 h.hasWasmExitStorm=()=>false;h.preparedCompleteWasm=true;
 const state=h.wasmJit.methodState({method:caller});
 state.meta={normalFlowFullyCompiled:true,fullyCompiled:false};
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(caller),false,'normal-flow-only caller remains excluded');
 state.meta.fullyCompiled=true;
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(caller),true,'complete prepared caller can use existing module');
 h.hasReadyFullWasmModule=()=>false;
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(caller),false,'complete metadata is insufficient without ready executable module');
 h.hasReadyFullWasmModule=()=>true;h.hasWasmExitStorm=()=>true;
 t.equal(h.hasPreparedLoopLeafWasmUpgrade(caller),false,'complete caller retains exit-storm fallback');
 t.end();
});
