'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const{splitReferenceLocalLifetimes:split}=require('../src/decompiler/primitiveLocalLifetimeRecovery');

test('reference phases preserve original null initialization, types and every expression',()=>{
 for(const type of ['Object','String','Object[]','int[]','java.util.List<String>']){
  const source=`${type} value=null;value=first();use(value);value=second();use(value);`,r=split(source,{retainDiagnostics:true});assert.equal(r.localsSplit,1,type);assert.equal(r.declarationsAdded,1);assert.equal(r.diagnostics.locals[0].type,type);assert.ok(r.source.startsWith(type+' value=null;'));assert.ok(r.source.includes(type+' valueLifetime1;'));assert.equal(split(r.source).localsSplit,0);assert.equal(split(source).source,r.source);
  const undo=r.source.replace(type+' valueLifetime1;\n','').replaceAll('valueLifetime1','value');assert.equal(undo,source);
 }
 const source='Object value=null;use(value);value=next();use(value);';assert.equal(split(source).declarationsAdded,1,'the original initialized first phase may read null');
 assert.equal(split('Object value=new Object();value=first();use(value);value=second();use(value);').localsSplit,0,'initializers beyond literal null need a separate contract');
});
test('nested phases stay within one block while preserving surrounding handlers and monitors',()=>{
 for(const protect of [s=>`try{${s}}catch(RuntimeException e){handle(e);}finally{finish();}`,s=>`synchronized(lock){${s}}`,s=>`try{try{${s}}finally{finish();}}finally{finish();}`]){
  const source='Object value=null;'+protect('value=first();use(value);value=second();use(value);'),r=split(source,{retainDiagnostics:true});assert.equal(r.declarationsAdded,1,source);assert.equal(r.diagnostics.locals[0].nested,true);assert.ok(r.source.includes('valueLifetime1=second();use(valueLifetime1)'));
 }
 for(const source of ['Object value=null;try{value=first();use(value);}finally{value=second();use(value);}','Object value=null;try{value=first();use(value);value=second();use(value);}catch(RuntimeException e){use(value);}','Object value=null;value=first();try{value=second();use(value);}finally{finish();}use(value);'])assert.equal(split(source).source,source);
});
test('reaching values, loop carry, conditional resets, aliases, shadows and captures remain sound',()=>{
 for(const source of ['Object x=null;x=first();if(flag)x=second();use(x);','Object x=null;while(flag){use(x);x=next(x);}use(x);','Object x=null;x=first();use(x);x=next(x);use(x);','Object x=null;x=first();use(x);if(flag)x=second();use(x);','Object x=null;x=first();use(x);x=second();use(this.x+x);','Object x=null;x=first();use(x);Runnable r=()->use(x);x=second();use(x);','Object x=null;x=first();use(x);{Object x=second();use(x);}','Object x=null;x=first();use(x);/* keep */x=second();use(x);','Object x=null;x=first();use(x);x=second();use(x);// keep\n'])assert.equal(split(source).source,source);
 const source='Object x=null;Object alias=null;x=first();alias=x;use(alias);x=second();use(x);use(alias);';const r=split(source);assert.equal(r.declarationsAdded,1);assert.ok(r.source.includes('alias=x'));assert.ok(r.source.endsWith('use(alias);'));
 assert.match(split('Object x=null;x=first();use(x);x=second();use(x);',{reservedNames:['xLifetime1']}).source,/Object xLifetime2;/);
});
test('native reference phases match independent alias and partial-failure models in protected bodies',()=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reference-phases-native-'));
 const run=(cmd,args)=>{const output=path.join(dir,'out'),error=path.join(dir,'err'),fds=[output,error].map(f=>fs.openSync(f,'w'));try{const r=spawnSync(cmd,args,{stdio:['ignore',...fds]});if(r.error)throw r.error;assert.equal(r.status,0,fs.readFileSync(error,'utf8'));return fs.readFileSync(output,'utf8').trim();}finally{fds.forEach(fd=>fs.closeSync(fd));}};
 const protects=[s=>s,s=>`try{${s}}catch(IllegalStateException e){event(8);if(e!=FAILURE)throw e;}finally{event(9);}`,s=>`synchronized(lock){${s}}`,s=>`try{${s}}finally{event(9);if(mode==1)return snapshot();if(mode==2)throw OVERRIDE;}`];
 const body='seen(x);x=choose(first);alias=x;touch(x);x=choose(second);seen(x);seen(alias);x=choose(first);while(index<limit){touch(x);index++;}x=choose(second);seen(x);array=chooseArray(firstArray);touchArray(array);array=chooseArray(secondArray);touchArray(array);';
 const oracle='seen(null);Node initial=choose(first);Node saved=initial;touch(initial);Node following=choose(second);seen(following);seen(saved);Node repeated=choose(first);while(index<limit){touch(repeated);index++;}Node ending=choose(second);seen(ending);Node[] initialArray=chooseArray(firstArray);touchArray(initialArray);Node[] followingArray=chooseArray(secondArray);touchArray(followingArray);';
 try{let methods='';for(let i=0;i<protects.length;i++){const source='Node x=null;Node alias=null;Node[] array=null;'+protects[i](body)+'return snapshot();',r=split(source);assert.equal(r.localsSplit,2,source);assert.ok(r.declarationsAdded>=4);for(const[name,code]of[['old',source],['next',r.source],['oracle',protects[i](oracle)+'return snapshot();']])methods+=`static String ${name}${i}(int limit,int mode){${code}}\n`;}
 const java=`public class ReferencePhases{static class Node{int id,value;Node(int i){id=i;}}static Node first,second;static Node[] firstArray,secondArray;static int index,count,failAt;static StringBuilder trace;static Object lock;static final RuntimeException FAILURE=new IllegalStateException(),OVERRIDE=new IllegalStateException();static void event(int n){trace.append(n).append(lock!=null&&Thread.holdsLock(lock)?"L":"U");if(count++==failAt)throw FAILURE;}static Node choose(Node n){event(1);return n;}static Node[] chooseArray(Node[] n){event(2);return n;}static void seen(Node n){event(n==null?0:n.id);}static void touch(Node n){event(3);n.value++;event(n.value);}static void touchArray(Node[] a){event(4);a[0].value++;event(a[0].value);}static String snapshot(){return index+":"+count+":"+(first==null?"n":first.value)+":"+(second==null?"n":second.value)+":"+(first==second)+":"+(firstArray==secondArray)+":"+trace;}${methods}
 static String take(int kind,int variant,int limit,int mode,int shape,boolean nullLock){first=(shape&1)==0?new Node(11):null;second=(shape&2)==0?new Node(12):null;if((shape&4)!=0)second=first;firstArray=(shape&8)==0?new Node[]{first}:null;secondArray=(shape&16)==0?new Node[]{second}:null;if((shape&32)!=0)secondArray=firstArray;index=count=0;lock=nullLock?null:new Object();trace=new StringBuilder();String result;try{switch(kind){${protects.map((_,i)=>`case ${i}:result=variant==0?old${i}(limit,mode):variant==1?next${i}(limit,mode):oracle${i}(limit,mode);break;`).join('')}default:throw new AssertionError();}}catch(Throwable e){result=e==FAILURE?"failure":e==OVERRIDE?"override":e.getClass().getName();}if(lock!=null&&Thread.holdsLock(lock))throw new AssertionError("monitor retained");return result+":"+snapshot();}
 public static void main(String[]args){int cases=0;for(int kind=0;kind<${protects.length};kind++)for(int limit=-1;limit<=3;limit++)for(int mode=0;mode<3;mode++)for(int shape=0;shape<64;shape++)for(int failure=-1;failure<24;failure++)for(boolean nullLock:new boolean[]{false,true}){failAt=failure;String expected=take(kind,2,limit,mode,shape,nullLock);for(int variant=0;variant<2;variant++)if(!expected.equals(take(kind,variant,limit,mode,shape,nullLock)))throw new AssertionError(kind+":"+variant+":"+shape+":"+failure+":"+expected);cases++;}System.out.println(cases);}}
 `;fs.writeFileSync(path.join(dir,'ReferencePhases.java'),java);run('javac',['--release','8','-d',dir,path.join(dir,'ReferencePhases.java')]);assert.equal(run('java',['-Xmx128m','-cp',dir,'ReferencePhases']),'192000');
 }finally{fs.rmSync(dir,{recursive:true,force:true});}
});
