'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const{foldSharedGuardedFallbacks:fold,foldTerminalGuardedFrameExits:terminal}=require('../src/decompiler/javaAstEmitter');const{shareExistingExitTails:finish}=require('../src/decompiler/cfr')._internals;
const sample=(nested=true,shared=true)=>'Frame:{before();'+(nested?'if(outer()){':'')+'if(choose()){'+(shared?'if(early())break Frame;':'')+'prefix();if(keep())break Frame;}fallback(false);'+(nested?'}':'')+'}';

test('normal emission retains other exits while placing a bounded callback in exclusive arms',()=>{
 const source=sample(),body=[source];finish(body);assert.equal(body[0],'before();if(outer()){if(choose()){if (!early()) {prefix();if (!keep()) {fallback(false);}}} else {fallback(false);}}');const next=fold(source,{retainDiagnostics:true});assert.equal(next.guardsRecovered,1);assert.equal(next.labelsRemoved,0);assert.equal(next.sharedFramesRetained,1);assert.equal(next.fallbackCallSitesAdded,1);assert.equal(terminal(next.source).labelsRemoved,1);assert.equal(fold(next.source).guardsRecovered,0);
});
test('direct, nested and labeled terminal corridors preserve prefixes and scopes',()=>{
 for(const source of[sample(false),sample(true,false),'if(outer())'+sample(false,false)+'else other();','Frame:{Object payload=read();if(choose()){prefix();if(keep())break Frame;}fallback(payload);}',sample().replace('if(outer()){','Alias:{')]){const next=fold(source,{retainDiagnostics:true});assert.equal(next.guardsRecovered,1,source);assert.equal(fold(next.source).guardsRecovered,0);}
});
test('other prefix references retain their exact frame and protected constructs',()=>{
 const source='Frame:{if(first())break Frame;if(choose()){try{prefix();}finally{cleanup();}if(keep())break Frame;}fallback(payload);}';const next=fold(source,{retainDiagnostics:true});assert.equal(next.sharedFramesRetained,1);assert.ok(next.source.includes('if(first())break Frame;'));assert.ok(next.source.includes('try{prefix();}finally{cleanup();}'));assert.equal(next.source.split('choose()').length-1,1);assert.equal(next.source.split('keep()').length-1,1);
});
test('nonterminal/protected corridors, shadowing declarations and unsupported callbacks refuse',()=>{
 for(const source of[sample().replace('fallback(false);}','fallback(false);}after();'),
  'Frame:{while(run()){if(choose()){prefix();if(keep())break Frame;}fallback(false);}}',
  'Frame:{try{if(choose()){prefix();if(keep())break Frame;}fallback(false);}finally{cleanup();}}',
  sample().replace('prefix();','Object payload=read();'),sample().replace('fallback(false);','fallback(value+1);'),
  sample().replace('fallback(false);','fallback((byte)2);'),sample().replace('fallback(false);','fallback(read());'),
  sample().replace('fallback(false);','get().fallback();'),sample().replace('fallback(false);','fallback(false);other();'),
  sample().replace('prefix();if(keep())break Frame;','try{prefix();if(keep())break Frame;}finally{cleanup();}'),
  sample()+' //comment\n',sample()+'\\u000a',sample()+'Runnable r=()->work();',sample()+' '.repeat(400001)])assert.equal(fold(source).source,source,source.slice(0,100));
});
test('diagnostics identify the sole callback clone, retained name and terminal corridor',()=>{
 const source=sample(),next=fold(source,{retainDiagnostics:true}),d=next.diagnostics;assert.deepEqual(d.corridorKinds,['IfStatement','BlockStatement']);assert.equal(d.labelRetained,true);assert.equal(d.frameScopeRetained,true);assert.equal(source.slice(d.jumpRange.start,d.jumpRange.end),'break Frame;');const copies=d.segments.filter(s=>s.copy);assert.equal(copies.length,1);assert.equal(source.slice(copies[0].range.start,copies[0].range.end),'fallback(false);');assert.ok(!Object.hasOwn(fold(source),'diagnostics'));assert.equal(fold(source,{retainDiagnostics:1}).guardsRecovered,0);
});
test('native shared callbacks preserve early exits, mutations, unboxing, overloads, aliases and finally priority',()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'shared-fallback-native-'));
 const run=(cmd,args)=>{const files=['out','err'].map(n=>path.join(directory,n)),fds=files.map(f=>fs.openSync(f,'w'));try{const r=spawnSync(cmd,args,{stdio:['ignore',...fds]});if(r.error)throw r.error;assert.equal(r.status,0,fs.readFileSync(files[1],'utf8'));return fs.readFileSync(files[0],'utf8').trim();}finally{fds.forEach(fd=>fs.closeSync(fd));}};
 const contexts=[s=>s,s=>`try{${s}}finally{event(7);if(mode==1)return snapshot();if(mode==2)throw OVERRIDE;}`,s=>`synchronized(lock){event(6);${s}}`,s=>`try{${s}}catch(IllegalStateException error){event(8);if(error!=FAILURE)throw error;}finally{event(7);}`,s=>`try{synchronized(lock){event(6);${s}}}finally{event(7);if(mode==1)return snapshot();if(mode==2)throw OVERRIDE;}`,s=>`{Object alias=handler;${s}if(alias!=originalHandler)throw new AssertionError();}`];
 try{let methods='',models=0;for(const protect of contexts)for(const nested of [false,true]){
   const active='if(probe(conditionBox)){if(early(earlyBox))break Frame;prefix(seed,inject);if(keep(guardBox,inject))break Frame;}handler.fallback(payload);';
   const source=protect('Frame:{before();'+(nested?'if(outer(outerBox)){'+active+'}':active)+'}event(3);')+'return snapshot();',next=fold(source);assert.equal(next.guardsRecovered,1);assert.equal(next.sharedFramesRetained,1);const clean=terminal(next.source);assert.equal(clean.guardsRecovered,1);assert.equal(clean.labelsRemoved,1);
   const dispatch='boolean selected=probe(conditionBox);boolean use=true;if(selected){boolean leave=early(earlyBox);if(leave){use=false;}else{prefix(seed,inject);use=!keep(guardBox,inject);}}if(use)handler.fallback(payload);';
   const oracle=protect('before();'+(nested?'if(outer(outerBox)){'+dispatch+'}':dispatch)+'event(3);')+'return snapshot();';
   for(const[name,body]of[['old',source],['next',next.source],['clean',clean.source],['oracle',oracle]])methods+=`static String ${name}${models}(Boolean outerBox,Boolean conditionBox,Boolean earlyBox,Boolean guardBox,int seed,int inject,int mode){${body}}\n`;models++;
  }
  const java=`public class SharedFallbackNative{static int value,effects,fallbacks;static boolean conditionField;static Object lock;static StringBuilder trace;static Integer payload;static Handler handler,originalHandler;static final RuntimeException FAILURE=new IllegalStateException(),OVERRIDE=new IllegalStateException();static void event(int n){effects=effects*31+n;trace.append((char)('a'+n));}static void before(){event(9);}static boolean outer(Boolean b){event(10);return b.booleanValue();}static boolean probe(Boolean b){event(0);conditionField=b.booleanValue();return conditionField;}static boolean early(Boolean b){event(5);return b.booleanValue();}static void prefix(int seed,int inject){event(1);value=value+seed;conditionField=!conditionField;if(inject==1)throw FAILURE;}static boolean keep(Boolean b,int inject){event(2);if(inject==2)throw FAILURE;return b.booleanValue();}static String snapshot(){return value+":"+effects+":"+fallbacks+":"+conditionField+":"+trace;}static class Handler{void fallback(Integer p){if(++fallbacks>1)throw new AssertionError("repeated fallback");event(4);value=value+p.intValue();}void fallback(Object p){throw new AssertionError("wrong overload");}}
${methods}
static String take(int kind,int variant,Boolean outerBox,Boolean conditionBox,Boolean earlyBox,Boolean guardBox,int seed,int inject,int mode,boolean nullLock,boolean nullPayload){value=seed;effects=seed;fallbacks=0;conditionField=false;trace=new StringBuilder();lock=nullLock?null:new Object();payload=nullPayload?null:Integer.valueOf(seed);handler=new Handler();originalHandler=handler;String result;try{switch(kind){${Array.from({length:models},(_,i)=>`case ${i}:result=variant==0?old${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode):variant==1?next${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode):variant==2?clean${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode):oracle${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode);break;`).join('')}default:throw new AssertionError();}}catch(Throwable error){result=error==FAILURE?"failure":error==OVERRIDE?"override":error.getClass().getName();}if(lock!=null&&Thread.holdsLock(lock))throw new AssertionError("monitor leaked");return result+":"+snapshot();}
public static void main(String[]args){int cases=0;for(int kind=0;kind<${models};kind++)for(Boolean outerBox:new Boolean[]{false,true,null})for(Boolean conditionBox:new Boolean[]{false,true,null})for(Boolean earlyBox:new Boolean[]{false,true,null})for(Boolean guardBox:new Boolean[]{false,true,null})for(int seed:new int[]{Integer.MIN_VALUE,-1,0,1,Integer.MAX_VALUE})for(int inject=0;inject<3;inject++)for(int mode=0;mode<3;mode++)for(boolean nullLock:new boolean[]{false,true})for(boolean nullPayload:new boolean[]{false,true}){String want=take(kind,3,outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode,nullLock,nullPayload);for(int variant=0;variant<3;variant++){String got=take(kind,variant,outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode,nullLock,nullPayload);if(!want.equals(got))throw new AssertionError(kind+":"+variant+":"+outerBox+":"+conditionBox+":"+earlyBox+":"+guardBox+":"+seed+":"+inject+":"+mode+":"+want+":"+got);}cases++;}System.out.println(cases+" cases / ${models} models");}}
`;
  const file=path.join(directory,'SharedFallbackNative.java');fs.writeFileSync(file,java);run('javac',['--release','8','-d',directory,file]);assert.equal(run('java',['-Xmx128m','-cp',directory,'SharedFallbackNative']),'174960 cases / 12 models');
 }finally{fs.rmSync(directory,{recursive:true,force:true});}
});
