'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const{foldSharedStoreFallbacks:fold,foldTerminalGuardedFrameExits:terminal}=require('../src/decompiler/javaAstEmitter');const{shareExistingExitTails:finish}=require('../src/decompiler/cfr')._internals;
const fields={owner:'Game',fields:[{name:'direction',type:'int',static:false},{name:'wide',type:'double',static:false},{name:'boxed',type:'Integer',static:false}]};
const sample=(nested=true)=>'Frame:{'+(nested?'if(outer()){':'')+'if(choose()){if(early())break Frame;prefix();this.direction=1;if(keep())break Frame;}this.direction=-1;'+(nested?'}':'')+'}';

test('normal emission finishes shared primitive stores with an ordinary early condition',()=>{
 const source=sample(),body=[source];finish(body,[],[],fields);assert.equal(body[0],'if(outer()){if(choose()){if (!(early())) {prefix();this.direction=1;if (!(keep())) {this.direction=-1;}}} else {this.direction=-1;}}');const next=fold(source,{ownedFields:fields,retainDiagnostics:true});assert.equal(next.framesRecovered,1);assert.equal(next.sharedFramesRetained,1);assert.equal(next.labelsRemoved,0);assert.equal(terminal(next.source).labelsRemoved,1);
});
test('one through eight scoped integral/boolean stores retain order and declaration scopes',()=>{
 for(const fallback of ['x=220;','x=220;y=-2147483648;flag=false;','x=220;'.repeat(8)]){const source='int x=0;int y=0;boolean flag=true;Frame:{if(choose()){if(early())break Frame;prefix();if(keep())break Frame;}'+fallback+'}',next=fold(source,{retainDiagnostics:true});assert.equal(next.framesRecovered,1);assert.equal(next.sharedFramesRetained,1);assert.equal(next.source.split('choose()').length-1,1);assert.equal(next.source.split('keep()').length-1,1);}
 assert.equal(fold('if(outer())'+sample(false)+'else other();',{ownedFields:fields}).framesRecovered,1);assert.equal(fold(sample(),{ownedFields:{...fields,owner:'pkg.Game'}}).framesRecovered,1);
});
test('other frame references and whole protected prefixes stay intact',()=>{
 const source='Frame:{if(first())break Frame;if(choose()){try{prefix();}finally{cleanup();}if(keep())break Frame;}this.direction=-1;}',next=fold(source,{ownedFields:fields});assert.equal(next.sharedFramesRetained,1);assert.ok(next.source.includes('if(first())break Frame;'));assert.ok(next.source.includes('try{prefix();}finally{cleanup();}'));
});
test('unknown/boxing/floating/computed stores, shadowing and crossed boundaries refuse',()=>{
 for(const source of[sample().replace('this.direction=-1;','this.wide=2.0;'),sample().replace('this.direction=-1;','this.boxed=220;'),sample().replace('this.direction=-1;','other.direction=-1;'),sample().replace('this.direction=-1;','this.direction=this.direction+1;'),sample().replace('this.direction=-1;','this.direction=read();'),sample().replace('this.direction=-1;','this.direction=(int)wide;'),sample().replace('prefix();','int direction=read();'),
 'Frame:{while(run()){if(choose()){prefix();if(keep())break Frame;}this.direction=-1;}}','Frame:{try{if(choose()){prefix();if(keep())break Frame;}this.direction=-1;}finally{cleanup();}}',
 sample().replace('this.direction=-1;}','this.direction=-1;}after();'),sample()+' //comment\n',sample()+'\\u000a',sample()+'Runnable r=()->work();',sample()+' '.repeat(400001)])assert.equal(fold(source,{ownedFields:fields}).source,source,source.slice(0,100));
});
test('diagnostics identify every store clone and retained frame',()=>{
 const source=sample(),next=fold(source,{ownedFields:fields,retainDiagnostics:true}),d=next.diagnostics;assert.deepEqual(d.corridorKinds,['IfStatement','BlockStatement']);assert.equal(d.labelRetained,true);assert.equal(d.frameScopeRetained,true);assert.equal(next.fallbackAssignmentsCopied,1);assert.equal(next.fallbackIdentifierCopiesAdded,1);assert.equal(d.segments.filter(s=>s.copy).length,1);assert.equal(source.slice(d.fallbackRange.start,d.fallbackRange.end),'this.direction=-1;');assert.ok(!Object.hasOwn(fold(source,{ownedFields:fields}),'diagnostics'));
});
test('native shared stores preserve nullable early exits, mutations, partial writes and finally priority',()=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'shared-store-native-'));
 const run=(cmd,args)=>{const files=['out','err'].map(n=>path.join(directory,n)),fds=files.map(f=>fs.openSync(f,'w'));try{const r=spawnSync(cmd,args,{stdio:['ignore',...fds]});if(r.error)throw r.error;assert.equal(r.status,0,fs.readFileSync(files[1],'utf8'));return fs.readFileSync(files[0],'utf8').trim();}finally{fds.forEach(fd=>fs.closeSync(fd));}};
 const contexts=[s=>s,s=>`try{${s}}finally{event(7);if(mode==1)return snapshot(x,y);if(mode==2)throw OVERRIDE;}`,s=>`synchronized(lock){event(6);${s}}`,s=>`try{${s}}catch(IllegalStateException error){event(8);if(error!=FAILURE)throw error;}finally{event(7);}`,s=>`try{synchronized(lock){event(6);${s}}}finally{event(7);if(mode==1)return snapshot(x,y);if(mode==2)throw OVERRIDE;}`,s=>`{Object alias=lock;${s}if(alias!=lock)throw new AssertionError();}`];
 const prefix='event(1);x=x+seed;y=y-1;conditionField=!conditionField;if(inject==1)throw FAILURE;',fallbacks=['x=220;y=-2147483648;','thisFlag=false;x=seed;y=220;'];
 try{let methods='',models=0;for(const protect of contexts)for(const nested of [false,true])for(const fallback of fallbacks){
   const active='if(probe(conditionBox)){if(early(earlyBox))break Frame;'+prefix+'if(keep(guardBox,inject))break Frame;}'+fallback;
   const source='int x=seed;int y=seed;'+protect('Frame:{'+(nested?'if(outer(outerBox)){'+active+'}':active)+'}event(3);')+'return snapshot(x,y);',next=fold(source,{parameters:[{name:'seed',type:'int'}],ownedFields:{owner:'SharedStoreNative',fields:[{name:'thisFlag',type:'boolean',static:true}]}});assert.equal(next.framesRecovered,1);assert.equal(next.sharedFramesRetained,1);const clean=terminal(next.source);assert.equal(clean.guardsRecovered,1);assert.equal(clean.labelsRemoved,1);
   const selection='boolean selected=probe(conditionBox);boolean use=true;if(selected){boolean leave=early(earlyBox);if(leave)use=false;else{'+prefix+'use=!keep(guardBox,inject);}}if(use){'+fallback+'}';
   const oracle='int x=seed;int y=seed;'+protect((nested?'if(outer(outerBox)){'+selection+'}':selection)+'event(3);')+'return snapshot(x,y);';for(const[name,body]of[['old',source],['next',next.source],['clean',clean.source],['oracle',oracle]])methods+=`static String ${name}${models}(Boolean outerBox,Boolean conditionBox,Boolean earlyBox,Boolean guardBox,int seed,int inject,int mode){${body}}\n`;models++;
  }
  const java=`public class SharedStoreNative{static boolean conditionField;static volatile boolean thisFlag;static int effects;static Object lock;static StringBuilder trace;static final RuntimeException FAILURE=new IllegalStateException(),OVERRIDE=new IllegalStateException();static void event(int n){effects=effects*31+n;trace.append((char)('a'+n));}static boolean outer(Boolean b){event(10);return b.booleanValue();}static boolean probe(Boolean b){event(0);conditionField=b.booleanValue();return conditionField;}static boolean early(Boolean b){event(5);return b.booleanValue();}static boolean keep(Boolean b,int inject){event(2);if(inject==2)throw FAILURE;return b.booleanValue();}static String snapshot(int x,int y){return x+":"+y+":"+effects+":"+conditionField+":"+thisFlag+":"+trace;}
${methods}
static String take(int kind,int variant,Boolean outerBox,Boolean conditionBox,Boolean earlyBox,Boolean guardBox,int seed,int inject,int mode,boolean nullLock){effects=seed;trace=new StringBuilder();lock=nullLock?null:new Object();conditionField=false;thisFlag=true;String result;try{switch(kind){${Array.from({length:models},(_,i)=>`case ${i}:result=variant==0?old${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode):variant==1?next${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode):variant==2?clean${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode):oracle${i}(outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode);break;`).join('')}default:throw new AssertionError();}}catch(Throwable error){result=error==FAILURE?"failure":error==OVERRIDE?"override":error.getClass().getName();}if(lock!=null&&Thread.holdsLock(lock))throw new AssertionError("monitor leaked");return result+":"+effects+":"+thisFlag+":"+trace;}
public static void main(String[]args){int cases=0;for(int kind=0;kind<${models};kind++)for(Boolean outerBox:new Boolean[]{false,true,null})for(Boolean conditionBox:new Boolean[]{false,true,null})for(Boolean earlyBox:new Boolean[]{false,true,null})for(Boolean guardBox:new Boolean[]{false,true,null})for(int seed:new int[]{Integer.MIN_VALUE,-1,0,1,Integer.MAX_VALUE})for(int inject=0;inject<3;inject++)for(int mode=0;mode<3;mode++)for(boolean nullLock:new boolean[]{false,true}){String want=take(kind,3,outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode,nullLock);for(int variant=0;variant<3;variant++){String got=take(kind,variant,outerBox,conditionBox,earlyBox,guardBox,seed,inject,mode,nullLock);if(!want.equals(got))throw new AssertionError(kind+":"+variant+":"+outerBox+":"+conditionBox+":"+earlyBox+":"+guardBox+":"+seed+":"+inject+":"+mode+":"+want+":"+got);}cases++;}System.out.println(cases+" cases / ${models} models");}}
`;
  const file=path.join(directory,'SharedStoreNative.java');fs.writeFileSync(file,java);run('javac',['--release','8','-d',directory,file]);assert.equal(run('java',['-Xmx128m','-cp',directory,'SharedStoreNative']),'174960 cases / 24 models');
 }finally{fs.rmSync(directory,{recursive:true,force:true});}
});
