const test = require('tape');
const {JVM} = require('../src/core/jvm');
const Stack = require('../src/core/stack');
const object = require('../src/instructions/object');
const instructions = require('../src/instructions');

test('synchronous static writes preserve declaring storage and lifecycle barriers', t => {
  const jvm = new JVM({jit: {enabled: false, compileWorker: false}});
  const parent = {ast: {classes: [{superClassName: null, items: []}]}, staticFields: new Map([['value:I', 3]])};
  const child = {ast: {classes: [{superClassName: 'Parent', items: []}]}, staticFields: new Map()};
  jvm.classes.Parent = parent; jvm.classes.Child = child;
  const instruction = {op: 'putstatic', arg: ['Field', 'Child', ['value', 'I']]};
  const frame = {stack: new Stack(), method: {name: 'set', descriptor: '()V'}, className: 'Child', pc: 1};
  const thread = {id: 7};
  frame.stack.push(42);
  t.equal(object.putstaticSync(frame, instruction, jvm, thread), object.SYNC_STATIC_FALLBACK, 'cold class retains canonical initialization');
  t.equal(frame.stack.peek(), 42, 'cold write does not consume the operand');
  jvm.classInitializationState.set('Child', 'INITIALIZING');
  jvm.classInitializationOwners.set('Child', 8);
  t.equal(object.putstaticSync(frame, instruction, jvm, thread), object.SYNC_STATIC_FALLBACK, 'another initializing thread remains a barrier');
  jvm.classInitializationOwners.set('Child', 7);
  let invalidated;
  jvm.jit.markStaticLocationChanged = (fields, key) => {invalidated = {fields, key};};
  t.equal(object.putstaticSync(frame, instruction, jvm, thread), undefined, 'own initializer writes synchronously');
  t.equal(parent.staticFields.get('value:I'), 42, 'inherited write reaches the declaring field');
  t.notOk(child.staticFields.has('value:I'), 'no shadow slot is introduced');
  t.equal(invalidated.fields, parent.staticFields, 'compiled readers receive the correct storage invalidation');
  t.equal(invalidated.key, 'value:I', 'invalidation identifies the field');
  t.ok(frame.stack.isEmpty(), 'successful write consumes exactly one value');
  t.throws(() => object.putstaticSync(frame, instruction, jvm, thread), /Stack underflow/, 'empty operand stack is diagnosed');
  jvm.classInitializationState.set('Child', 'ERRONEOUS');
  frame.stack.push(9);
  t.equal(object.putstaticSync(frame, instruction, jvm, thread), object.SYNC_STATIC_FALLBACK, 'cached site observes an erroneous class');
  t.equal(parent.staticFields.get('value:I'), 42, 'failed lifecycle check leaves storage unchanged');
  jvm.classInitializationState.set('Child', 'INITIALIZED');
  child.staticFields.set('value:I', 1);
  jvm.bumpClassEpoch();
  t.equal(object.putstaticSync(frame, instruction, jvm, thread), undefined, 'replacement metadata invalidates the cached declaring site');
  t.equal(child.staticFields.get('value:I'), 9, 'newly declared field receives the write');
  t.equal(parent.staticFields.get('value:I'), 42, 'old declaring storage remains unchanged');
  const code = [{instruction}];
  instructions.prepareSyncInstructions(code);
  t.equal(code[0][instructions.syncHandler], object.putstaticSync, 'interpreter burst dispatch uses the warm write path');
  t.end();
});
