;; Hand port of Deko Bloko's per-frame ray driver fh.a(IIZI)V and its callees
;; (ke.a, h.a, ok.a/b/c polygon rasterizer, hk.c span blend) with the guest
;; object model in linear memory: int[] = [length][elements], statics as
;; globals, callees as direct wasm calls, no imports on the hot path.
(module
  (memory (export "mem") 256)
  ;; hk statics (clip + raster)
  (global $hk_c (export "hk_c") (mut i32) (i32.const 0))
  (global $hk_g (export "hk_g") (mut i32) (i32.const 0))
  (global $hk_h (export "hk_h") (mut i32) (i32.const 0))
  (global $hk_b (export "hk_b") (mut i32) (i32.const 0))
  (global $hk_j (export "hk_j") (mut i32) (i32.const 0))
  (global $hk_l (export "hk_l") (mut i32) (i32.const 0)) ;; address of int[] header
  ;; ok statics
  (global $ok_b (mut i32) (i32.const 0))
  (global $ok_h (mut i32) (i32.const 0))
  (global $ok_d (mut i32) (i32.const 0))
  (global $ok_f (export "ok_f") (mut i32) (i32.const 0)) ;; address of int[] header or 0 (null)
  (global $ok_e (mut i32) (i32.const 0))
  (global $ok_g (mut i32) (i32.const 0))
  (global $ok_a (mut i32) (i32.const 0))
  (global $ok_c (mut i32) (i32.const 0))
  ;; other statics
  (global $rb_n (export "rb_n") (mut i32) (i32.const 0))
  (global $bb_f (export "bb_f") (mut i32) (i32.const 0))
  (global $client_A (export "client_A") (mut i32) (i32.const 0))
  (global $qg_b (export "qg_b") (mut i32) (i32.const 0))
  (global $qg_f (export "qg_f") (mut i32) (i32.const 0))
  ;; bump allocator
  (global $heap (export "heap") (mut i32) (i32.const 0))

  (func $alloc (export "alloc") (param $n i32) (result i32)
    (local $a i32)
    (local.set $a (global.get $heap))
    (global.set $heap (i32.add (local.get $a) (i32.add (i32.const 4) (i32.shl (local.get $n) (i32.const 2)))))
    (memory.fill (local.get $a) (i32.const 0) (i32.add (i32.const 4) (i32.shl (local.get $n) (i32.const 2))))
    (i32.store (local.get $a) (local.get $n))
    (local.get $a))

  ;; element address helpers
  (func $ea (param $arr i32) (param $i i32) (result i32)
    (i32.add (i32.add (local.get $arr) (i32.const 4)) (i32.shl (local.get $i) (i32.const 2))))
  (func $ld (param $arr i32) (param $i i32) (result i32)
    (i32.load (call $ea (local.get $arr) (local.get $i))))
  (func $st (param $arr i32) (param $i i32) (param $v i32)
    (i32.store (call $ea (local.get $arr) (local.get $i)) (local.get $v)))

  ;; ke.a(II)I
  (func $ke_a (param $p0 i32) (param $p1 i32) (result i32)
    (if (i32.ne (local.get $p0) (i32.const 2047)) (then nop)) ;; ke.h = null (dead static)
    (call $ld (global.get $qg_b) (i32.and (local.get $p1) (i32.const 2047))))
  ;; h.a(IB)I
  (func $h_a (param $p0 i32) (param $p1 i32) (result i32)
    (if (i32.ne (local.get $p1) (i32.const -122)) (then nop))
    (call $ld (global.get $qg_f) (i32.and (local.get $p0) (i32.const 2047))))

  ;; hk.c(IIIII)V horizontal alpha span
  (func $hk_c (param $x i32) (param $y i32) (param $w i32) (param $color i32) (param $alpha i32)
    (local $l5 i32) (local $l6 i32) (local $l7 i32) (local $l8 i32) (local $p i32) (local $addr i32) (local $end i32)
    (local $l9 i32) (local $l10 i32) (local $l11 i32)
    (if (i32.lt_s (local.get $y) (global.get $hk_h)) (then return))
    (if (i32.ge_s (local.get $y) (global.get $hk_b)) (then return))
    (if (i32.lt_s (local.get $x) (global.get $hk_c)) (then
      (local.set $w (i32.sub (local.get $w) (i32.sub (global.get $hk_c) (local.get $x))))
      (local.set $x (global.get $hk_c))))
    (if (i32.gt_s (i32.add (local.get $x) (local.get $w)) (global.get $hk_g)) (then
      (local.set $w (i32.sub (global.get $hk_g) (local.get $x)))))
    (local.set $l5 (i32.sub (i32.const 256) (local.get $alpha)))
    (local.set $l6 (i32.mul (i32.and (i32.shr_s (local.get $color) (i32.const 16)) (i32.const 255)) (local.get $alpha)))
    (local.set $l7 (i32.mul (i32.and (i32.shr_s (local.get $color) (i32.const 8)) (i32.const 255)) (local.get $alpha)))
    (local.set $l8 (i32.mul (i32.and (local.get $color) (i32.const 255)) (local.get $alpha)))
    (local.set $addr (call $ea (global.get $hk_l) (i32.add (local.get $x) (i32.mul (local.get $y) (global.get $hk_j)))))
    (local.set $end (i32.add (local.get $addr) (i32.shl (local.get $w) (i32.const 2))))
    (block $done (loop $L
      (br_if $done (i32.ge_s (local.get $addr) (local.get $end)))
      (local.set $p (i32.load (local.get $addr)))
      (local.set $l9 (i32.mul (i32.and (i32.shr_s (local.get $p) (i32.const 16)) (i32.const 255)) (local.get $l5)))
      (local.set $l10 (i32.mul (i32.and (i32.shr_s (local.get $p) (i32.const 8)) (i32.const 255)) (local.get $l5)))
      (local.set $l11 (i32.mul (i32.and (local.get $p) (i32.const 255)) (local.get $l5)))
      (i32.store (local.get $addr)
        (i32.add
          (i32.add (i32.shl (i32.shr_s (i32.add (local.get $l6) (local.get $l9)) (i32.const 8)) (i32.const 16))
                   (i32.shl (i32.shr_s (i32.add (local.get $l7) (local.get $l10)) (i32.const 8)) (i32.const 8)))
          (i32.shr_s (i32.add (local.get $l8) (local.get $l11)) (i32.const 8))))
      (local.set $addr (i32.add (local.get $addr) (i32.const 4)))
      (br $L))))

  ;; ok.b(II)V bubble sort of active edges by x
  (func $ok_b_sort (param $lo i32) (param $hi i32)
    (local $l2 i32) (local $l3 i32) (local $l4 i32) (local $l5 i32) (local $f i32)
    (local.set $f (global.get $ok_f))
    (block $ret (loop $outer
      (br_if $ret (i32.lt_s (local.get $hi) (i32.add (local.get $lo) (i32.const 8))))
      (local.set $l2 (i32.const 1))
      (local.set $l3 (i32.add (local.get $lo) (i32.const 4)))
      (block $d (loop $inner
        (br_if $d (i32.ge_s (local.get $l3) (local.get $hi)))
        (local.set $l4 (call $ld (local.get $f) (i32.sub (local.get $l3) (i32.const 4))))
        (local.set $l5 (call $ld (local.get $f) (local.get $l3)))
        (if (i32.gt_s (local.get $l4) (local.get $l5)) (then
          (local.set $l2 (i32.const 0))
          (call $st (local.get $f) (i32.sub (local.get $l3) (i32.const 4)) (local.get $l5))
          (call $st (local.get $f) (local.get $l3) (local.get $l4))
          (local.set $l4 (call $ld (local.get $f) (i32.sub (local.get $l3) (i32.const 2))))
          (call $st (local.get $f) (i32.sub (local.get $l3) (i32.const 2)) (call $ld (local.get $f) (i32.add (local.get $l3) (i32.const 2))))
          (call $st (local.get $f) (i32.add (local.get $l3) (i32.const 2)) (local.get $l4))
          (local.set $l4 (call $ld (local.get $f) (i32.sub (local.get $l3) (i32.const 1))))
          (call $st (local.get $f) (i32.sub (local.get $l3) (i32.const 1)) (call $ld (local.get $f) (i32.add (local.get $l3) (i32.const 3))))
          (call $st (local.get $f) (i32.add (local.get $l3) (i32.const 3)) (local.get $l4))))
        (local.set $l3 (i32.add (local.get $l3) (i32.const 4)))
        (br $inner)))
      (br_if $ret (local.get $l2))
      (local.set $hi (i32.sub (local.get $hi) (i32.const 4)))
      (br $outer))))

  ;; ok.a(II)V quicksort of edges by y0
  (func $ok_a_qsort (param $lo i32) (param $hi i32)
    (local $l2 i32) (local $l3 i32) (local $l4 i32) (local $l5 i32) (local $l6 i32) (local $l7 i32) (local $l8 i32) (local $f i32)
    (if (i32.le_s (local.get $hi) (i32.add (local.get $lo) (i32.const 4))) (then return))
    (local.set $f (global.get $ok_f))
    (local.set $l2 (local.get $lo))
    (local.set $l3 (call $ld (local.get $f) (local.get $l2)))
    (local.set $l4 (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 1))))
    (local.set $l5 (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 2))))
    (local.set $l6 (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 3))))
    (local.set $l7 (i32.add (local.get $lo) (i32.const 4)))
    (block $d (loop $L
      (br_if $d (i32.ge_s (local.get $l7) (local.get $hi)))
      (local.set $l8 (call $ld (local.get $f) (i32.add (local.get $l7) (i32.const 1))))
      (if (i32.lt_s (local.get $l8) (local.get $l4)) (then
        (call $st (local.get $f) (local.get $l2) (call $ld (local.get $f) (local.get $l7)))
        (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 1)) (local.get $l8))
        (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 2)) (call $ld (local.get $f) (i32.add (local.get $l7) (i32.const 2))))
        (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 3)) (call $ld (local.get $f) (i32.add (local.get $l7) (i32.const 3))))
        (local.set $l2 (i32.add (local.get $l2) (i32.const 4)))
        (call $st (local.get $f) (local.get $l7) (call $ld (local.get $f) (local.get $l2)))
        (call $st (local.get $f) (i32.add (local.get $l7) (i32.const 1)) (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 1))))
        (call $st (local.get $f) (i32.add (local.get $l7) (i32.const 2)) (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 2))))
        (call $st (local.get $f) (i32.add (local.get $l7) (i32.const 3)) (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 3))))))
      (local.set $l7 (i32.add (local.get $l7) (i32.const 4)))
      (br $L)))
    (call $st (local.get $f) (local.get $l2) (local.get $l3))
    (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 1)) (local.get $l4))
    (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 2)) (local.get $l5))
    (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 3)) (local.get $l6))
    (call $ok_a_qsort (local.get $lo) (local.get $l2))
    (call $ok_a_qsort (i32.add (local.get $l2) (i32.const 4)) (local.get $hi)))

  ;; ok.a()V scanline setup
  (func $ok_a_setup
    (local $l0 i32) (local $l1 i32) (local $l2 i32) (local $l3 i32) (local $l4 i32) (local $l5 i32) (local $l6 i32) (local $l7 i32) (local $l8 i32) (local $f i32)
    (if (i32.lt_s (global.get $ok_d) (i32.const 0)) (then
      (global.set $ok_g (i32.const 0)) (global.set $ok_b (i32.const 0)) (global.set $ok_c (i32.const 0))
      (global.set $ok_h (i32.const 2147483646)) (return)))
    (call $ok_a_qsort (i32.const 0) (global.get $ok_d))
    (local.set $f (global.get $ok_f))
    (local.set $l0 (call $ld (local.get $f) (i32.const 1)))
    (if (i32.lt_s (local.get $l0) (global.get $hk_h)) (then (local.set $l0 (global.get $hk_h))))
    (local.set $l1 (i32.const 0))
    (local.set $l2 (i32.const 0))
    (block $d (loop $L
      (br_if $d (i32.ge_s (local.get $l2) (global.get $ok_d)))
      (local.set $l3 (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 1))))
      (br_if $d (i32.lt_s (local.get $l0) (local.get $l3)))
      (local.set $l4 (call $ld (local.get $f) (local.get $l2)))
      (local.set $l5 (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 2))))
      (local.set $l6 (call $ld (local.get $f) (i32.add (local.get $l2) (i32.const 3))))
      (local.set $l7 (i32.div_s (i32.shl (i32.sub (local.get $l5) (local.get $l4)) (i32.const 16)) (i32.sub (local.get $l6) (local.get $l3))))
      (local.set $l8 (i32.add (i32.shl (local.get $l4) (i32.const 16)) (i32.const 32768)))
      (call $st (local.get $f) (local.get $l2) (i32.add (local.get $l8) (i32.mul (i32.sub (local.get $l0) (local.get $l3)) (local.get $l7))))
      (call $st (local.get $f) (i32.add (local.get $l2) (i32.const 2)) (local.get $l7))
      (local.set $l2 (i32.add (local.get $l2) (i32.const 4)))
      (br $L)))
    (global.set $ok_c (local.get $l1))
    (global.set $ok_b (local.get $l2))
    (global.set $ok_g (local.get $l2))
    (global.set $ok_h (i32.sub (local.get $l0) (i32.const 1))))

  ;; ok.b()Z next span
  (func $ok_b_step (result i32)
    (local $l0 i32) (local $l1 i32) (local $l2 i32) (local $l3 i32) (local $l4 i32) (local $l5 i32) (local $l6 i32) (local $l7 i32) (local $l8 i32) (local $l9 i32) (local $f i32)
    (local.set $f (global.get $ok_f))
    (local.set $l0 (global.get $ok_b))
    (local.set $l1 (global.get $ok_g))
    (local.set $l2 (global.get $ok_h))
    (loop $top
      (if (i32.lt_s (local.get $l1) (local.get $l0)) (then
        (global.set $ok_a (i32.shr_s (call $ld (local.get $f) (local.get $l1)) (i32.const 16)))
        (global.set $ok_e (i32.shr_s (call $ld (local.get $f) (i32.add (local.get $l1) (i32.const 4))) (i32.const 16)))
        (call $st (local.get $f) (local.get $l1) (i32.add (call $ld (local.get $f) (local.get $l1)) (call $ld (local.get $f) (i32.add (local.get $l1) (i32.const 2)))))
        (call $st (local.get $f) (i32.add (local.get $l1) (i32.const 4)) (i32.add (call $ld (local.get $f) (i32.add (local.get $l1) (i32.const 4))) (call $ld (local.get $f) (i32.add (local.get $l1) (i32.const 6)))))
        (local.set $l1 (i32.add (local.get $l1) (i32.const 8)))
        (global.set $ok_g (local.get $l1))
        (return (i32.const 1))))
      (local.set $l2 (i32.add (local.get $l2) (i32.const 1)))
      (global.set $ok_h (local.get $l2))
      (if (i32.ge_s (local.get $l2) (global.get $hk_b)) (then (return (i32.const 0))))
      (local.set $l3 (global.get $ok_c))
      (block $d1 (loop $L1
        (br_if $d1 (i32.ge_s (local.get $l0) (global.get $ok_d)))
        (local.set $l4 (call $ld (local.get $f) (i32.add (local.get $l0) (i32.const 1))))
        (br_if $d1 (i32.lt_s (local.get $l2) (local.get $l4)))
        (local.set $l5 (call $ld (local.get $f) (local.get $l0)))
        (local.set $l6 (call $ld (local.get $f) (i32.add (local.get $l0) (i32.const 2))))
        (local.set $l7 (call $ld (local.get $f) (i32.add (local.get $l0) (i32.const 3))))
        (local.set $l8 (i32.div_s (i32.shl (i32.sub (local.get $l6) (local.get $l5)) (i32.const 16)) (i32.sub (local.get $l7) (local.get $l4))))
        (local.set $l9 (i32.add (i32.shl (local.get $l5) (i32.const 16)) (i32.const 32768)))
        (call $st (local.get $f) (local.get $l0) (local.get $l9))
        (call $st (local.get $f) (i32.add (local.get $l0) (i32.const 2)) (local.get $l8))
        (local.set $l0 (i32.add (local.get $l0) (i32.const 4)))
        (br $L1)))
      (local.set $l4 (local.get $l3))
      (block $d2 (loop $L2
        (br_if $d2 (i32.ge_s (local.get $l4) (local.get $l0)))
        (local.set $l5 (call $ld (local.get $f) (i32.add (local.get $l4) (i32.const 3))))
        (if (i32.ge_s (local.get $l2) (local.get $l5)) (then
          (call $st (local.get $f) (local.get $l4) (call $ld (local.get $f) (local.get $l3)))
          (call $st (local.get $f) (i32.add (local.get $l4) (i32.const 1)) (call $ld (local.get $f) (i32.add (local.get $l3) (i32.const 1))))
          (call $st (local.get $f) (i32.add (local.get $l4) (i32.const 2)) (call $ld (local.get $f) (i32.add (local.get $l3) (i32.const 2))))
          (call $st (local.get $f) (i32.add (local.get $l4) (i32.const 3)) (call $ld (local.get $f) (i32.add (local.get $l3) (i32.const 3))))
          (local.set $l3 (i32.add (local.get $l3) (i32.const 4)))))
        (local.set $l4 (i32.add (local.get $l4) (i32.const 4)))
        (br $L2)))
      (if (i32.eq (local.get $l3) (global.get $ok_d)) (then (global.set $ok_d (i32.const 0)) (return (i32.const 0))))
      (call $ok_b_sort (local.get $l3) (local.get $l0))
      (global.set $ok_c (local.get $l3))
      (global.set $ok_b (local.get $l0))
      (local.set $l1 (local.get $l3))
      (br $top))
    (unreachable))

  ;; ok.a(II[I[I)V fill
  (func $ok_a_fill (param $color i32) (param $alpha i32) (param $l2 i32) (param $l3 i32)
    (local $l4 i32) (local $l5 i32) (local $l6 i32) (local $l7 i32)
    (call $ok_a_setup)
    (block $d (loop $L
      (br_if $d (i32.eqz (call $ok_b_step)))
      (local.set $l4 (global.get $ok_a))
      (local.set $l5 (global.get $ok_e))
      (local.set $l6 (global.get $ok_h))
      (if (local.get $l2) (then
        (local.set $l7 (i32.sub (local.get $l6) (global.get $hk_h)))
        (if (i32.lt_s (local.get $l4) (i32.add (call $ld (local.get $l2) (local.get $l7)) (global.get $hk_c)))
          (then (local.set $l4 (i32.add (call $ld (local.get $l2) (local.get $l7)) (global.get $hk_c)))))
        (if (i32.gt_s (local.get $l5) (i32.add (i32.add (call $ld (local.get $l2) (local.get $l7)) (call $ld (local.get $l3) (local.get $l7))) (global.get $hk_c)))
          (then (local.set $l5 (i32.add (i32.add (call $ld (local.get $l2) (local.get $l7)) (call $ld (local.get $l3) (local.get $l7))) (global.get $hk_c)))))))
      (call $hk_c (local.get $l4) (local.get $l6) (i32.sub (local.get $l5) (local.get $l4)) (local.get $color) (local.get $alpha))
      (br $L))))

  (func $ok_c (global.set $ok_d (i32.const 0)))

  ;; ok.b([III)V build edge list
  (func $ok_b_edges (param $pts i32) (param $off i32) (param $len i32)
    (local $l3 i32) (local $l4 i32) (local $l5 i32) (local $l6 i32) (local $l7 i32) (local $nf i32) (local $i i32) (local $f i32) (local $d i32)
    (local.set $l3 (i32.add (global.get $ok_d) (i32.shl (local.get $len) (i32.const 1))))
    (if (i32.or (i32.eqz (global.get $ok_f)) (i32.lt_s (i32.load (global.get $ok_f)) (local.get $l3))) (then
      (local.set $nf (call $alloc (local.get $l3)))
      (local.set $i (i32.const 0))
      (block $d (loop $L
        (br_if $d (i32.ge_s (local.get $i) (global.get $ok_d)))
        (call $st (local.get $nf) (local.get $i) (call $ld (global.get $ok_f) (local.get $i)))
        (local.set $i (i32.add (local.get $i) (i32.const 1)))
        (br $L)))
      (global.set $ok_f (local.get $nf))))
    (local.set $f (global.get $ok_f))
    (local.set $len (i32.add (local.get $len) (local.get $off)))
    (local.set $l4 (i32.sub (local.get $len) (i32.const 2)))
    (local.set $l5 (local.get $off))
    (block $d (loop $L
      (br_if $d (i32.ge_s (local.get $l5) (local.get $len)))
      (local.set $l6 (call $ld (local.get $pts) (i32.add (local.get $l4) (i32.const 1))))
      (local.set $l7 (call $ld (local.get $pts) (i32.add (local.get $l5) (i32.const 1))))
      (local.set $d (global.get $ok_d))
      (if (i32.lt_s (local.get $l6) (local.get $l7)) (then
        (call $st (local.get $f) (local.get $d) (call $ld (local.get $pts) (local.get $l4)))
        (call $st (local.get $f) (i32.add (local.get $d) (i32.const 1)) (local.get $l6))
        (call $st (local.get $f) (i32.add (local.get $d) (i32.const 2)) (call $ld (local.get $pts) (local.get $l5)))
        (call $st (local.get $f) (i32.add (local.get $d) (i32.const 3)) (local.get $l7))
        (global.set $ok_d (i32.add (local.get $d) (i32.const 4))))
      (else (if (i32.lt_s (local.get $l7) (local.get $l6)) (then
        (call $st (local.get $f) (local.get $d) (call $ld (local.get $pts) (local.get $l5)))
        (call $st (local.get $f) (i32.add (local.get $d) (i32.const 1)) (local.get $l7))
        (call $st (local.get $f) (i32.add (local.get $d) (i32.const 2)) (call $ld (local.get $pts) (local.get $l4)))
        (call $st (local.get $f) (i32.add (local.get $d) (i32.const 3)) (local.get $l6))
        (global.set $ok_d (i32.add (local.get $d) (i32.const 4)))))))
      (local.set $l4 (local.get $l5))
      (local.set $l5 (i32.add (local.get $l5) (i32.const 2)))
      (br $L))))

  ;; ok.a([IIIII[I[I)V
  (func $ok_a7 (param $pts i32) (param $off i32) (param $len i32) (param $color i32) (param $alpha i32) (param $l5 i32) (param $l6 i32)
    (if (local.get $l5) (then
      (if (i32.ne (i32.sub (global.get $hk_b) (global.get $hk_h)) (i32.load (local.get $l5))) (then unreachable))))
    (call $ok_c)
    (call $ok_b_edges (local.get $pts) (local.get $off) (local.get $len))
    (call $ok_a_fill (local.get $color) (local.get $alpha) (local.get $l5) (local.get $l6)))

  ;; ok.a([III)V
  (func $ok_a3 (param $pts i32) (param $color i32) (param $alpha i32)
    (call $ok_a7 (local.get $pts) (i32.const 0) (i32.load (local.get $pts)) (local.get $color) (local.get $alpha) (i32.const 0) (i32.const 0)))

  ;; fh.a(IIZI)V driver
  (func $fh_a (export "fh_a") (param $p0 i32) (param $p1 i32) (param $p2 i32) (param $p3 i32)
    (local $A i32) (local $l4 i32) (local $l5 i32) (local $l6 i32) (local $l7 i32) (local $l8 i32) (local $l9 i32) (local $l10 i32)
    (local $l11 i32) (local $l12 i32) (local $l13 i32) (local $l14 i32) (local $l15 i32) (local $arr i32) (local $n i32) (local $rb i32)
    (local.set $A (global.get $client_A))
    (if (i32.ne (local.get $p2) (i32.const 1)) (then return))
    (local.set $l4 (i32.const 320))
    (local.set $l5 (i32.const 490))
    (local.set $l6 (i32.const 0))
    (local.set $rb (global.get $rb_n))
    (block $d (loop $L
      (br_if $d (i32.le_s (i32.xor (local.get $l6) (i32.const -1)) (i32.xor (i32.load (local.get $rb)) (i32.const -1))))
      (local.set $n (call $ld (local.get $rb) (local.get $l6)))
      (local.set $l7 (i32.and (i32.shr_s (local.get $n) (i32.const 8)) (i32.const 255)))
      (local.set $l8 (i32.and (i32.const 255) (i32.shr_s (local.get $n) (i32.const 24))))
      (local.set $l9 (i32.sub (i32.shr_s (i32.mul (i32.const 2048) (local.get $l7)) (i32.const 8))
                              (i32.sub (i32.const 0) (i32.shr_s (i32.mul (global.get $bb_f) (i32.add (i32.const 1) (local.get $l8))) (i32.const 6)))))
      (local.set $l10 (i32.and (i32.shr_s (local.get $n) (i32.const 16)) (i32.const 255)))
      (local.set $l11 (i32.and (i32.const 255) (local.get $n)))
      (local.set $l12 (i32.shr_s (call $ke_a (i32.const 2047) (local.get $l9)) (i32.const 6)))
      (local.set $l13 (i32.shr_s (call $h_a (local.get $l9) (i32.const -122)) (i32.const 6)))
      (local.set $l14 (i32.shr_s (call $ke_a (i32.const 2047) (i32.add (local.get $l11) (local.get $l9))) (i32.const 6)))
      (local.set $l15 (i32.shr_s (call $h_a (i32.add (local.get $l9) (local.get $l11)) (i32.const -122)) (i32.const 6)))
      (local.set $arr (call $alloc (i32.const 6)))
      (call $st (local.get $arr) (i32.const 0) (i32.add (local.get $l4) (local.get $p3)))
      (call $st (local.get $arr) (i32.const 1) (i32.sub (local.get $p0) (i32.sub (i32.const 0) (local.get $l5))))
      (call $st (local.get $arr) (i32.const 2) (i32.add (local.get $l12) (local.get $p3)))
      (call $st (local.get $arr) (i32.const 3) (i32.add (local.get $p0) (local.get $l13)))
      (call $st (local.get $arr) (i32.const 4) (i32.sub (local.get $p3) (i32.sub (i32.const 0) (local.get $l14))))
      (call $st (local.get $arr) (i32.const 5) (i32.add (local.get $l15) (local.get $p0)))
      (br_if $d (local.get $A))
      (if (i32.ne (i32.const 256) (local.get $p1))
        (then (call $ok_a3 (local.get $arr) (i32.const 16777215) (i32.shr_s (i32.mul (local.get $l10) (i32.const 256)) (i32.const 9))))
        (else (call $ok_a3 (local.get $arr) (i32.const 16777215) (local.get $l10))))
      (local.set $l6 (i32.add (local.get $l6) (i32.const 1)))
      (br_if $L (i32.eqz (local.get $A))))))
)
