const jreClasses = {
  'java/lang/Object': require('./java/lang/Object'),
  'java/lang/System': require('./java/lang/System'),
  'java/lang/Class': require('./java/lang/Class'),
  'java/lang/String': require('./java/lang/String'),
  'java/lang/StringBuilder': require('./java/lang/StringBuilder'),
  'java/lang/Enum': require('./java/lang/Enum'),
  'java/lang/Runnable': require('./java/lang/Runnable'),
  'java/lang/Thread': require('./java/lang/Thread'),
  'java/lang/Throwable': require('./java/lang/Throwable'),
  'java/lang/Exception': require('./java/lang/Exception'),
  'java/lang/RuntimeException': require('./java/lang/RuntimeException'),
  'java/lang/ArithmeticException': require('./java/lang/ArithmeticException'),
  'java/lang/IllegalArgumentException': require('./java/lang/IllegalArgumentException'),
  'java/lang/NoSuchMethodException': require('./java/lang/NoSuchMethodException'),
  'java/lang/invoke/LambdaMetafactory': require('./java/lang/invoke/LambdaMetafactory'),
  'java/lang/invoke/StringConcatFactory': require('./java/lang/invoke/StringConcatFactory'),
  'java/lang/reflect/Method': require('./java/lang/reflect/Method'),
  'java/lang/Integer': require('./java/lang/Integer'),
  'java/lang/Appendable': require('./java/lang/Appendable'),
  'java/io/OutputStream': require('./java/io/OutputStream'),
  'java/io/FilterOutputStream': require('./java/io/FilterOutputStream'),
  'java/io/NullOutputStream': require('./java/io/NullOutputStream'),
  'java/io/ConsoleOutputStream': require('./java/io/ConsoleOutputStream'),
  'java/io/PrintStream': require('./java/io/PrintStream'),
  'java/io/InputStreamReader': require('./java/io/InputStreamReader'),
  'java/io/BufferedReader': require('./java/io/BufferedReader'),
  'java/io/BufferedInputStream': require('./java/io/BufferedInputStream'),
  'java/net/URL': require('./java/net/URL'),
  'java/net/URLConnection': require('./java/net/URLConnection'),
  'java/net/HttpURLConnection': require('./java/net/HttpURLConnection'),
  'java/util/LinkedList': require('./java/util/LinkedList'),
  'java/util/Objects': require('./java/util/Objects'),
};

module.exports = jreClasses;
