'use strict';
// Port of make/jdk/src/classes/build/tools/methodhandle/
// VarHandleGuardMethodGenerator.java, which writes
// java/lang/invoke/VarHandleGuards.java. The Java tool reflects over its own
// VarHandleTemplate interface (not over the boot JDK's VarHandle), so the
// same interface is described here as data, in declaration order (the order
// Class.getMethods() returned in the reference build).
//
// usage: VarHandleGuardMethodGenerator VarHandleGuards.java
const fs = require('fs');
const { LNSEP } = require('./util');

// interface VarHandleTemplate: return type ('Object' = the variable type)
// and number of parameters (each of the variable type)
const VAR_HANDLE_TEMPLATE = [
  { name: 'get', ret: 'Object', params: 0 },
  { name: 'set', ret: 'void', params: 1 },
  { name: 'compareAndSet', ret: 'boolean', params: 2 },
  { name: 'compareAndExchange', ret: 'Object', params: 2 },
  { name: 'getAndUpdate', ret: 'Object', params: 1 },
];

// receiver + intermediate coordinates of each shape (null = static)
const HANDLE_TYPES = [
  ['Object'],
  [null],
  ['Object', 'int'],
  ['Object', 'long'],
  ['Object', 'long', 'long'],
];

// the 5 JVM calling convention types
const BASIC_TYPES = ['Object', 'int', 'long', 'float', 'double'];

// TypeKind.from(c).upperBound().descriptorString().charAt(0)
const CHAR_TYPE = {
  Object: 'L', int: 'I', long: 'J', float: 'F', double: 'D', boolean: 'Z',
  void: 'V', byte: 'I', short: 'I', char: 'I',
};

const CLASS_HEADER = `/*
 * Copyright (c) 2014, 2025, Oracle and/or its affiliates. All rights reserved.
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 * This code is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 2 only, as
 * published by the Free Software Foundation.  Oracle designates this
 * particular file as subject to the "Classpath" exception as provided
 * by Oracle in the LICENSE file that accompanied this code.
 *
 * This code is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * version 2 for more details (a copy is included in the LICENSE file that
 * accompanied this code).
 *
 * You should have received a copy of the GNU General Public License version
 * 2 along with this work; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
 * or visit www.oracle.com if you need additional information or have any
 * questions.
 */
package java.lang.invoke;

import jdk.internal.vm.annotation.AOTSafeClassInitializer;
import jdk.internal.vm.annotation.ForceInline;
import jdk.internal.vm.annotation.Hidden;

// This file is generated by build.tools.methodhandle.VarHandleGuardMethodGenerator.
// Do not edit!
@AOTSafeClassInitializer
final class VarHandleGuards {
`;

const GUARD_METHOD_SIG_TEMPLATE = '<RETURN> <NAME>_<SIGNATURE>(<PARAMS>)';

const GUARD_METHOD_TEMPLATE = `@ForceInline
@LambdaForm.Compiled
@Hidden
static final <METHOD> throws Throwable {
    boolean direct = handle.checkAccessModeThenIsDirect(ad);
    if (direct && handle.vform.methodType_table[ad.type] == ad.symbolicMethodTypeErased) {
        <RESULT_ERASED>MethodHandle.linkToStatic(<LINK_TO_STATIC_ARGS>);<RETURN_ERASED>
    } else {
        MethodHandle mh = handle.getMethodHandle(ad.mode);
        <RETURN>mh.asType(ad.symbolicMethodTypeInvoker).invokeBasic(<LINK_TO_INVOKER_ARGS>);
    }
}`;

const GUARD_METHOD_TEMPLATE_V = `@ForceInline
@LambdaForm.Compiled
@Hidden
static final <METHOD> throws Throwable {
    boolean direct = handle.checkAccessModeThenIsDirect(ad);
    if (direct && handle.vform.methodType_table[ad.type] == ad.symbolicMethodTypeErased) {
        MethodHandle.linkToStatic(<LINK_TO_STATIC_ARGS>);
    } else if (direct && handle.vform.getMethodType_V(ad.type) == ad.symbolicMethodTypeErased) {
        MethodHandle.linkToStatic(<LINK_TO_STATIC_ARGS>);
    } else {
        MethodHandle mh = handle.getMethodHandle(ad.mode);
        mh.asType(ad.symbolicMethodTypeInvoker).invokeBasic(<LINK_TO_INVOKER_ARGS>);
    }
}`;

function generateMethodType(m, receiver, value, intermediates) {
  const params = [];
  if (receiver !== null) params.push(receiver);
  params.push(...intermediates);
  for (let i = 0; i < m.params; i++) params.push(value);
  return { ret: m.ret === 'Object' ? value : m.ret, params };
}

// String.indent(n) for n > 0
const indent = (s, n) => s.split(/\r\n|\r|\n/).map(l => ' '.repeat(n) + l + '\n').join('');

function generateMethod(mt) {
  const paramNames = ['handle', ...mt.params.map((_, i) => 'arg' + i)];
  const paramTypes = ['VarHandle', ...mt.params];
  const PARAMS = paramNames.map((n, i) => paramTypes[i] + ' ' + n)
    .concat('VarHandle.AccessDescriptor ad').join(', ');
  const SIGNATURE = mt.params.map(p => CHAR_TYPE[p]).join('') + '_' + CHAR_TYPE[mt.ret];
  const METHOD = GUARD_METHOD_SIG_TEMPLATE.replace('<RETURN>', mt.ret).replace('<NAME>', 'guard')
    .replace('<SIGNATURE>', SIGNATURE).replace('<PARAMS>', PARAMS);
  const linkToStaticArgs = [...paramNames, 'handle.vform.getMemberName(ad.mode)'];
  const linkToInvokerArgs = [...paramNames];
  linkToInvokerArgs[0] += '.asDirect()';
  const r = mt.ret;
  const RETURN = r === 'void' ? '' : r === 'Object' ? 'return ' : 'return (' + r + ') ';
  const RESULT_ERASED = r === 'void' ? '' : r !== 'Object' ? 'return (' + r + ') ' : 'Object r = ';
  const RETURN_ERASED = r !== 'Object' ? '' : '\n        return ad.returnType.cast(r);';
  const template = r === 'void' ? GUARD_METHOD_TEMPLATE_V : GUARD_METHOD_TEMPLATE;
  return indent(template.replace('<METHOD>', METHOD)
    .split('<RETURN>').join(RETURN)
    .replace('<RESULT_ERASED>', RESULT_ERASED)
    .replace('<RETURN_ERASED>', RETURN_ERASED)
    .split('<LINK_TO_STATIC_ARGS>').join(linkToStaticArgs.join(', '))
    .replace('<LINK_TO_INVOKER_ARGS>', linkToInvokerArgs.join(', ')), 4);
}

function generate() {
  let out = CLASS_HEADER + LNSEP;
  const seen = new Set();
  for (const m of VAR_HANDLE_TEMPLATE) {
    for (const [receiver, ...intermediates] of HANDLE_TYPES) {
      for (const bt of BASIC_TYPES) {
        const mt = generateMethodType(m, receiver, bt, intermediates);
        const key = mt.ret + '(' + mt.params.join(',') + ')';
        if (seen.has(key)) continue;
        seen.add(key);
        out += generateMethod(mt) + LNSEP;
      }
    }
  }
  return out + '}' + LNSEP;
}

function main(args) {
  if (args.length !== 1) {
    process.stderr.write('Usage: java VarHandleGuardMethodGenerator VarHandleGuards.java' + LNSEP);
    return 1;
  }
  fs.writeFileSync(args[0], generate());
  return 0;
}

module.exports = { main, generate };
